In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
file_path = '/content/drive/My Drive/myData/owid-covid-data.csv'




In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from scipy import stats
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error, accuracy_score, precision_score
veri = pd.read_csv(file_path)

In [ ]:
veri.loc[0:4,"new_cases_smoothed"]=0
veri.head(10)
df1=pd.DataFrame(veri)
newCasesAfghanistan = df1[df1['location'] == 'Afghanistan']
newCasesAfghanistan = newCasesAfghanistan['new_cases']
newCasesAfghanistan = newCasesAfghanistan[newCasesAfghanistan.index % 7 == 0]
newCasesAfghanistan.head(50)


0         0.0
7         0.0
14        0.0
21        0.0
28        0.0
35        0.0
42        0.0
49        0.0
56        1.0
63        0.0
70        6.0
77       17.0
84       67.0
91      183.0
98      247.0
105     387.0
112     422.0
119     841.0
126    1392.0
133    2490.0
140    3813.0
147    4577.0
154    5108.0
161    4551.0
168    4195.0
175    2319.0
182    2056.0
189    1679.0
196     938.0
203     747.0
210     674.0
217     305.0
224     536.0
231     343.0
238     249.0
245     161.0
252     337.0
259     278.0
266     273.0
273     105.0
280     406.0
287     438.0
294     627.0
301     657.0
308     608.0
315    1002.0
322    1468.0
329    1463.0
336    1675.0
343    1311.0
Name: new_cases, dtype: float64

In [ ]:
df2 = pd.DataFrame(veri)
newDeathsAfghanistan = df2[df2['location'] =='Afghanistan']
newDeathsAfghanistan = newDeathsAfghanistan['new_deaths']
newDeathsAfghanistan = newDeathsAfghanistan[newDeathsAfghanistan.index % 7 == 0]
newDeathsAfghanistan.head(50)

df3 = pd.DataFrame(veri)
newCasesSmoothedAfghanistan = df3[df3['location'] =='Afghanistan']
newCasesSmoothedAfghanistan = newCasesSmoothedAfghanistan['new_cases_smoothed']
newCasesSmoothedAfghanistan = newCasesSmoothedAfghanistan[newCasesSmoothedAfghanistan.index % 7 == 0]

df4 = pd.DataFrame(veri)
diabetesPrevalenceAfghanistan = df4[df4['location'] =='Afghanistan']
diabetesPrevalenceAfghanistan = diabetesPrevalenceAfghanistan['diabetes_prevalence']
diabetesPrevalenceAfghanistan = diabetesPrevalenceAfghanistan[diabetesPrevalenceAfghanistan.index % 7 == 0]

df5 = pd.DataFrame(veri)
cardiovascDeathRateAfghanistan = df5[df5['location'] =='Afghanistan']
cardiovascDeathRateAfghanistan = cardiovascDeathRateAfghanistan['cardiovasc_death_rate']
cardiovascDeathRateAfghanistan = cardiovascDeathRateAfghanistan[cardiovascDeathRateAfghanistan.index % 7 == 0]

df6 = pd.DataFrame(veri)
PoPulationAfghanistan = df6[df6['location'] =='Afghanistan']
PoPulationAfghanistan = PoPulationAfghanistan['population']
PoPulationAfghanistan = PoPulationAfghanistan[PoPulationAfghanistan.index % 7 == 0]

#Ölçeklendirme-normalizasyon
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
newCasesAfghanistan = newCasesAfghanistan.values
newCasesAfghanistan = newCasesAfghanistan.reshape(-1, 1)
newCasesAfghanistan = scaler.fit_transform(newCasesAfghanistan)


newCasesSmoothedAfghanistan = newCasesSmoothedAfghanistan.values
newCasesSmoothedAfghanistan = newCasesSmoothedAfghanistan.reshape(-1, 1)
newCasesSmoothedAfghanistan = scaler.fit_transform(newCasesSmoothedAfghanistan)


diabetesPrevalenceAfghanistan = diabetesPrevalenceAfghanistan.values
diabetesPrevalenceAfghanistan = diabetesPrevalenceAfghanistan.reshape(-1, 1)
diabetesPrevalenceAfghanistan = scaler.fit_transform(diabetesPrevalenceAfghanistan)


cardiovascDeathRateAfghanistan = cardiovascDeathRateAfghanistan.values
cardiovascDeathRateAfghanistan = cardiovascDeathRateAfghanistan.reshape(-1, 1)
cardiovascDeathRateAfghanistan = scaler.fit_transform(cardiovascDeathRateAfghanistan)


PoPulationAfghanistan = PoPulationAfghanistan.values
PoPulationAfghanistan = PoPulationAfghanistan.reshape(-1, 1)
PoPulationAfghanistan = scaler.fit_transform(PoPulationAfghanistan)


X = np.column_stack((newCasesAfghanistan, newCasesSmoothedAfghanistan, diabetesPrevalenceAfghanistan, cardiovascDeathRateAfghanistan, PoPulationAfghanistan))
print(X.shape)


y =  (newDeathsAfghanistan)
print(y.shape)
#eğitim ve test veri setlerinin ayrılması
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=44)

y_train = np.array(y_train)
y_test = np.array(y_test)
y_train = scaler.fit_transform(y_train.reshape(-1, 1))
y_test = scaler.fit_transform(y_test.reshape(-1, 1))
print(len(X_test))
print(len(X_train))

(220, 5)
(220,)
66
154


In [ ]:
import time
from keras.models import Sequential
from keras.layers import Dense
import keras
from keras.losses import binary_crossentropy

In [ ]:
param_grid = {
    'n_activation': ("relu","sigmoid","tanh")

}

In [ ]:
best_score = float('inf')
best_params = None

for n_activation in param_grid['n_activation']:

  siniflandirici = Sequential()
  siniflandirici.add(Dense(units=6, activation=n_activation, input_dim=5))#ilk katman 5 giris
  siniflandirici.add(Dense(units=6, activation=n_activation))
  siniflandirici.add(Dense(units=6, activation=n_activation))
  siniflandirici.add(Dense(units=6, activation=n_activation))
  siniflandirici.add(Dense(units=1, activation=n_activation))  # Son katman, tek sınıf

  siniflandirici.compile(optimizer='adam', loss=binary_crossentropy, metrics=['accuracy'])

  siniflandirici.fit(X_train, y_train, batch_size=10, epochs=100)

  Y_pred_Ysa = siniflandirici.predict(X_test)

  mse=mean_squared_error(y_test, Y_pred_Ysa)

  if mse < best_score:
            best_score = mse
            best_params = {'n_activation': n_activation}
print("En iyi parametreler:", best_params)

print("En iyi skor:", best_score)


Epoch 1/100
16/16 [==============================] - 2s 5ms/step - loss: 0.7942 - accuracy: 0.1429
Epoch 2/100
16/16 [==============================] - 0s 5ms/step - loss: 0.7942 - accuracy: 0.1429
Epoch 3/100
16/16 [==============================] - 0s 3ms/step - loss: 0.7942 - accuracy: 0.1429
Epoch 4/100
16/16 [==============================] - 0s 3ms/step - loss: 0.7942 - accuracy: 0.1429
Epoch 5/100
16/16 [==============================] - 0s 4ms/step - loss: 0.7942 - accuracy: 0.1429
Epoch 6/100
16/16 [==============================] - 0s 4ms/step - loss: 0.7942 - accuracy: 0.1429
Epoch 7/100
16/16 [==============================] - 0s 4ms/step - loss: 0.7942 - accuracy: 0.1429
Epoch 8/100
16/16 [==============================] - 0s 5ms/step - loss: 0.7942 - accuracy: 0.1429
Epoch 9/100
16/16 [==============================] - 0s 6ms/step - loss: 0.7942 - accuracy: 0.1429
Epoch 10/100
16/16 [==============================] - 0s 5ms/step - loss: 0.7942 - accuracy: 0.1429
Epoch 11/

KeyboardInterrupt: 

In [ ]:
siniflandirici = Sequential()
siniflandirici.add(Dense(units=6, activation="relu", input_dim=5))#ilk katman 5 giris
siniflandirici.add(Dense(units=6, activation="relu"))
siniflandirici.add(Dense(units=6, activation="relu"))
siniflandirici.add(Dense(units=6, activation="relu"))
siniflandirici.add(Dense(units=1, activation="relu"))  # Son katman, tek sınıf
siniflandirici.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

start_time = time.time()

siniflandirici.fit(X_train, y_train, batch_size=10, epochs=100)

end_time = time.time()

# Bir epok için geçen süreyi hesapla
epoch_time = end_time - start_time
print(f" eğitim için geçen süre: {epoch_time:.2f} saniye")

Epoch 1/100
16/16 [==============================] - 1s 2ms/step - loss: 0.1838 - accuracy: 0.1429
Epoch 2/100
16/16 [==============================] - 0s 3ms/step - loss: 0.1710 - accuracy: 0.1429
Epoch 3/100
16/16 [==============================] - 0s 2ms/step - loss: 0.1656 - accuracy: 0.1429
Epoch 4/100
16/16 [==============================] - 0s 3ms/step - loss: 0.1612 - accuracy: 0.1429
Epoch 5/100
16/16 [==============================] - 0s 3ms/step - loss: 0.1567 - accuracy: 0.1429
Epoch 6/100
16/16 [==============================] - 0s 3ms/step - loss: 0.1526 - accuracy: 0.1429
Epoch 7/100
16/16 [==============================] - 0s 3ms/step - loss: 0.1483 - accuracy: 0.1429
Epoch 8/100
16/16 [==============================] - 0s 3ms/step - loss: 0.1453 - accuracy: 0.1429
Epoch 9/100
16/16 [==============================] - 0s 2ms/step - loss: 0.1417 - accuracy: 0.1429
Epoch 10/100
16/16 [==============================] - 0s 3ms/step - loss: 0.1403 - accuracy: 0.1429
Epoch 11/

**Test Verisi Üzerindeki Tahminler**

In [ ]:
Y_pred_Ysa = siniflandirici.predict(X_test)

3/3 [==============================] - 0s 6ms/step


**Performans Değerlendirmesi**

In [ ]:
r2_score(y_test, Y_pred_Ysa)

0.7284213563777052

In [ ]:
mean_absolute_error(y_test, Y_pred_Ysa)

0.05067630496929691

In [ ]:
mean_squared_error(y_test, Y_pred_Ysa)

0.010221954459757886

In [ ]:
siniflandirici = Sequential()
siniflandirici.add(Dense(units=6, activation='relu', input_dim=5))#ilk katman 5 giris
siniflandirici.add(Dense(units=6, activation='relu'))
siniflandirici.add(Dense(units=6, activation='relu'))
siniflandirici.add(Dense(units=6, activation='relu'))
siniflandirici.add(Dense(units=1, activation='relu'))  # Son katman, tek sınıf
siniflandirici.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
siniflandirici.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
16/16 [==============================] - 1s 2ms/step - loss: 0.2307 - accuracy: 0.1429
Epoch 2/100
16/16 [==============================] - 0s 3ms/step - loss: 0.1983 - accuracy: 0.1429
Epoch 3/100
16/16 [==============================] - 0s 2ms/step - loss: 0.1924 - accuracy: 0.1429
Epoch 4/100
16/16 [==============================] - 0s 3ms/step - loss: 0.1895 - accuracy: 0.1429
Epoch 5/100
16/16 [==============================] - 0s 2ms/step - loss: 0.1851 - accuracy: 0.1429
Epoch 6/100
16/16 [==============================] - 0s 3ms/step - loss: 0.1802 - accuracy: 0.1429
Epoch 7/100
16/16 [==============================] - 0s 4ms/step - loss: 0.1747 - accuracy: 0.1429
Epoch 8/100
16/16 [==============================] - 0s 4ms/step - loss: 0.1699 - accuracy: 0.1429
Epoch 9/100
16/16 [==============================] - 0s 4ms/step - loss: 0.1647 - accuracy: 0.1429
Epoch 10/100
16/16 [==============================] - 0s 4ms/step - loss: 0.1607 - accuracy: 0.1429
Epoch 11/

In [ ]:
for i in siniflandirici.layers:
  ilk_gizli_katman = siniflandirici.layers[0].get_weights()
  ikinci_gizli_katman = siniflandirici.layers[1].get_weights()
  cıktı_katmani = siniflandirici.layers[2].get_weights()

In [ ]:
ilk_gizli_katman

[array([[-0.24191499,  0.19219863,  0.5191104 , -0.06728142, -0.6320033 ,
         -0.4652935 ],
        [ 0.5484609 , -0.387073  ,  0.6024563 ,  0.29340333,  0.63503367,
         -0.7351717 ],
        [ 0.42195433, -0.4947428 ,  0.28932112,  0.6943757 ,  0.01102847,
          0.41586238],
        [ 0.43665165, -0.6000073 , -0.37781364, -0.38419968, -0.02499282,
         -0.2731961 ],
        [-0.24389982,  0.5293507 , -0.5739595 , -0.62665176,  0.37508804,
         -0.22530115]], dtype=float32),
 array([0., 0., 0., 0., 0., 0.], dtype=float32)]

In [ ]:
ikinci_gizli_katman

[array([[-0.00758898,  0.22440636, -0.49630898, -0.0162316 , -0.18375534,
         -0.5365056 ],
        [-0.29077095, -0.3581506 ,  0.48215014, -0.50655437,  0.01825327,
          0.5837763 ],
        [-0.49233973, -0.63369894,  0.4762997 ,  0.31262463,  0.52840704,
          0.50551635],
        [-0.35666147,  0.50068444, -0.3675141 ,  0.5970734 ,  0.2563026 ,
          0.12108839],
        [-0.66093254, -0.4890476 ,  0.06365031,  0.4405232 ,  0.19747955,
          0.4501887 ],
        [-0.5336266 ,  0.48449212,  0.39003724, -0.41258696, -0.0388909 ,
          0.64700705]], dtype=float32),
 array([0., 0., 0., 0., 0., 0.], dtype=float32)]

In [ ]:
cıktı_katmani

[array([[ 0.6112785 , -0.47263998,  0.37804574, -0.61351144,  0.58668476,
         -0.37260494],
        [-0.48367637, -0.69437116,  0.49172622,  0.5288488 , -0.40207487,
          0.10615695],
        [-0.21072024, -0.5806172 ,  0.6111868 ,  0.5718798 , -0.5832672 ,
          0.12312698],
        [-0.6292295 ,  0.12237352, -0.11344498, -0.01444674,  0.45956463,
         -0.41808408],
        [-0.5134582 ,  0.64795095,  0.10465974,  0.5666453 ,  0.5165835 ,
         -0.49481225],
        [ 0.68929785, -0.28413686, -0.5018361 ,  0.53378516, -0.69520366,
         -0.00517511]], dtype=float32),
 array([0., 0., 0., 0., 0., 0.], dtype=float32)]


**Tersine Ölçeklendirme**

In [ ]:
ters_olceklendirme=scaler.inverse_transform(Y_pred_Ysa.reshape(-1,1))

In [ ]:
ters_olceklendirme

array([[ -3.0974414 ],
       [ -2.085308  ],
       [ -2.3855677 ],
       [ -1.6911477 ],
       [ -3.5527258 ],
       [ -6.2427325 ],
       [-10.566609  ],
       [ -3.801834  ],
       [ -0.83963245],
       [ -8.140493  ],
       [ -2.2105174 ],
       [ -7.4636154 ],
       [-19.271648  ],
       [-35.938095  ],
       [-10.32824   ],
       [ -4.1067677 ],
       [ -1.0087389 ],
       [-33.108307  ],
       [ -1.1966748 ],
       [  0.        ],
       [-25.358568  ],
       [ -5.0256443 ],
       [-10.911352  ],
       [ -3.1162276 ],
       [ -4.212552  ],
       [  0.        ],
       [ -2.99144   ],
       [  0.        ],
       [-24.878494  ],
       [-27.331411  ],
       [ -3.428088  ],
       [ -3.0974412 ],
       [ -1.4596585 ],
       [-10.982461  ],
       [ -7.9395413 ],
       [ -1.4971974 ],
       [ -9.085639  ],
       [ -0.8333454 ],
       [ -2.391684  ],
       [ -5.0752316 ],
       [ -2.5980165 ],
       [ -1.0838547 ],
       [ -3.3531644 ],
       [ -0

In [ ]:
Y_pred_Ysa

array([[-0.00586637],
       [-0.00394945],
       [-0.00451812],
       [-0.00320293],
       [-0.00672865],
       [-0.01182336],
       [-0.02001252],
       [-0.00720044],
       [-0.00159021],
       [-0.0154176 ],
       [-0.00418659],
       [-0.01413564],
       [-0.03649933],
       [-0.06806457],
       [-0.01956106],
       [-0.00777797],
       [-0.00191049],
       [-0.06270513],
       [-0.00226643],
       [ 0.        ],
       [-0.04802759],
       [-0.00951827],
       [-0.02066544],
       [-0.00590195],
       [-0.00797832],
       [ 0.        ],
       [-0.00566561],
       [ 0.        ],
       [-0.04711836],
       [-0.05176404],
       [-0.00649259],
       [-0.00586637],
       [-0.0027645 ],
       [-0.02080012],
       [-0.01503701],
       [-0.0028356 ],
       [-0.01720765],
       [-0.00157831],
       [-0.0045297 ],
       [-0.00961218],
       [-0.00492049],
       [-0.00205276],
       [-0.00635069],
       [-0.00186316],
       [-0.01107605],
       [-0